# Generated by Django 5.0.4 on 2024-07-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_Name', models.CharField(blank=True, max_length=100)),
                ('c_Address', models.CharField(blank=True, max_length=200)),
                ('c_DOB', models.DateField(blank=True, null=True)),
                ('c_Aadhaar', models.CharField(blank=True, max_length=100)),
                ('c_Phone', models.CharField(blank=True, max_length=100)),
                ('c_Institution', models.CharField(blank=True, max_length=100)),
                ('c_Stream', models.CharField(blank=True, max_length=100)),
                ('c_RegNo', models.CharField(blank=True, max_length=100)),
                ('c_CGPA', models.FloatField(blank=True, null=True)),
                ('c_Semester', models.CharField(blank=True, max_length=100)),
                ('c_PassoutYear', models.DateField(blank=True, null=True)),
                ('c_Photo', models.ImageField(upload_to='pics/')),
                ('c_Resume', models.FileField(upload_to='pics/')),
                ('c_Marklist', models.FileField(upload_to='pics/')),
                ('c_SecQues', models.CharField(blank=True, max_length=100)),
                ('c_Ans', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
