# Generated by Django 5.0.4 on 2024-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='c_PassoutYear',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
