# Generated by Django 5.0.4 on 2024-07-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_c_marklist_alter_candidate_c_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=100)),
                ('v_dept', models.CharField(max_length=100)),
                ('v_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='c_Marklist',
            field=models.FileField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='c_Photo',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='c_Resume',
            field=models.FileField(upload_to='pics/'),
        ),
    ]
