# Generated by Django 5.0.4 on 2024-07-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_placements_volunteer_alter_candidate_c_marklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='c_Marklist',
            field=models.FileField(upload_to='marklists/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='c_Resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
