# Generated by Django 5.0.4 on 2024-07-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_alter_candidate_c_marklist_alter_candidate_c_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='c_Photo',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
